version: "3.8"
services:
  usdg-mysql:
    image: mysql:5.7
    ports:
      - "33061:3306"
    volumes:
      - ./mysql/.data:/var/lib/mysql
    networks:
        appNetwork:
            ipv4_address: 172.24.2.1
    environment:
      MYSQL_DATABASE: usdg
      MYSQL_USER: usdg
      MYSQL_PASSWORD: usdg
      MYSQL_ROOT_PASSWORD: usdg
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: usdg-mysql
  dev:
    container_name: api-usdg
    image: api-usdg
    build:
        context: .
        target: development
        dockerfile: ../Dockerfile
    command: npm run start:debug
    ports:
        - 3500:3500
    networks:
        appNetwork:
            ipv4_address: 172.24.2.2
    volumes:
        - ../.:/usr/src/app
        # - /usr/src/app/node_modules
    depends_on: 
        - 'usdg-mysql'
    restart: unless-stopped

networks:
    appNetwork:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.24.2.0/16"